<!-- as generated by the old version -->
<!-- Danach: Anzeige datenerfassung2 -->

<form method=post action="/datenerfassung/default">

<div id=bodyleft>
<p class=side>Bitte füllen Sie für jeden Betrieb/Betriebsteil des Unternehmens
ein Formular aus.<br>Die Fomulare werden anonym ausgewertet.</p>
</div>

<div id=bodymain>
<input type=hidden name=id value="129">
<div class=defaultbutton><input type=submit name=save value=save></div>

<div class=input><label class=left>Firma</label>
<input type=text class=text name=company
	value="CHMS GmbH &amp; Co. KG">
<input type=submit class=button name=new
	value="Daten für einen weiteren Betrieb erfassen">
</div>

<div class=input><label class=left>Betrieb</label>
<input type=text class=text name=name
	value="CHMS Rödental / ReWaMem Pilotanlage">
<input type=submit class=button name=select
	value="Vorhandene Betriebsdaten bearbeiten">
</div>

<div class=input>
<label class="left factorytype">Art des Betriebes</label>
<div class=radioopts>
<input type=radio class=radio name=type value=1 id=type-1
	 checked	><label for=type-1></label>
	<label for=type-1>Wäscherei</label>
<input type=radio class=radio name=type value=2 id=type-2
		><label for=type-2></label>
	<label for=type-2>Reinigung</label>
<input type=radio class=radio name=type value=3 id=type-3
		><label for=type-3></label>
	<label for=type-3>Mischbetrieb</label>
</div>
</div>
<script src="/components/com_oekobench/views/default/tmpl/datesel.js?1"
	></script>

<input type=hidden name=contact value="">
<input type=hidden name=phone value="">
<input type=hidden name=email value="">


<p>&nbsp;</p>
<div class=input>
<label class=left>&nbsp;</label>
<div class=opts><b>Bitte markieren Sie die Verbünde, in denen
Ihr Unternehmen Mitglied ist:</b><br>&nbsp;</div></div>

<div class=input id="mydataorg">
<label class=left>&nbsp;</label>
<div class="opts">
<div class=opt>
	<input type=checkbox class=check name="org[]" value="0" id="org-0"
		 checked	><label for="org-0"></label>
	<label for="org-0">ohne</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="servitex" id="org-servitex"
			><label for="org-servitex"></label>
	<label for="org-servitex">Servitex</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="sitex" id="org-sitex"
			><label for="org-sitex"></label>
	<label for="org-sitex">Sitex</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="dressline" id="org-dressline"
			><label for="org-dressline"></label>
	<label for="org-dressline">Dressline</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="nwdzentratex" id="org-nwdzentratex"
			><label for="org-nwdzentratex"></label>
	<label for="org-nwdzentratex">NWD Zentratex</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="lavantex" id="org-lavantex"
			><label for="org-lavantex"></label>
	<label for="org-lavantex">Lavantex</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="tsa" id="org-tsa"
			><label for="org-tsa"></label>
	<label for="org-tsa">TSA</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="leosystem" id="org-leosystem"
			><label for="org-leosystem"></label>
	<label for="org-leosystem">Leosystem</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="dbl" id="org-dbl"
			><label for="org-dbl"></label>
	<label for="org-dbl">DBL</label>
</div>
<div class=opt>
	<input type=checkbox class=check name="org[]" value="diemietwaesche.de" id="org-diemietwaesche.de"
			><label for="org-diemietwaesche.de"></label>
	<label for="org-diemietwaesche.de">diemietwaesche.de</label>
</div>
</div><div class=clearer></div></div>
<script>
(function(){
var e = document.getElementById('mydataorg');
if (!e)
	return;
var boxes = e.getElementsByTagName('INPUT');
for (var i = 0; i < boxes.length; i++) {
	var box = boxes[i];
	box.onchange = box.onclick = (function(box) { return function() {
		setTimeout(function(){
			if (boxes[0] == box && box.checked) {
				for (var i = 1; i < boxes.length; i++)
					boxes[i].checked = false;
				return;
			}
			var num = 0;
			for (var i = 1; i < boxes.length; i++)
				if (boxes[i].checked)
					num++;
			boxes[0].checked = num == 0;
		}, 100);
		box.blur();
		return true;
	}; })(box);
}
})();
</script>

<p>&nbsp;</p>
<div class=input>
<label class=left>&nbsp;</label>
<div class=opts id=worklabel>
<b>Bitte markieren Sie die Arbeitsweisen, die für Sie
typisch sind:</b><br>&nbsp;</div></div>

<div id=for-type-1>
<div class=input>
<label class=left>&nbsp;</label>
<div class=opts>
<input type=checkbox class=check name="work[]" id="work1-wtabwasserfrisch"
	value="wtabwasserfrisch" checked><label for="work1-wtabwasserfrisch"></label>
	<label for="work1-wtabwasserfrisch"
	>Wärmetauscher Abwasser zu Frischwasser</label><br>
<input type=checkbox class=check name="work[]" id="work1-wrabluftzufrisch"
	value="wrabluftzufrisch"><label for="work1-wrabluftzufrisch"></label>
	<label for="work1-wrabluftzufrisch"
	>Wärmerückgewinnung Abluft zu Frischluft</label><br>
<input type=checkbox class=check name="work[]" id="work1-wrabluftzuwasser"
	value="wrabluftzuwasser"><label for="work1-wrabluftzuwasser"></label>
	<label for="work1-wrabluftzuwasser"
	>Wärmerückgewinnung Abluft zu Wasser</label><br>
<input type=checkbox class=check name="work[]" id="work1-wasserrueck"
	value="wasserrueck" checked><label for="work1-wasserrueck"></label>
	<label for="work1-wasserrueck"
	>Wasserrückgewinnung</label><br>
<input type=checkbox class=check name="work[]" id="work1-wassermehrfach"
	value="wassermehrfach" checked><label for="work1-wassermehrfach"></label>
	<label for="work1-wassermehrfach"
	>Wassermehrfachnutzung</label><br>
<input type=checkbox class=check name="work[]" id="work1-abwassersiebfilter"
	value="abwassersiebfilter"><label for="work1-abwassersiebfilter"></label>
	<label for="work1-abwassersiebfilter"
	>Abwasserbehandlung: Siebfilter</label><br>
<input type=checkbox class=check name="work[]" id="work1-abwasserfaellung"
	value="abwasserfaellung"><label for="work1-abwasserfaellung"></label>
	<label for="work1-abwasserfaellung"
	>Abwasserbehandlung: Fällung/Flockung</label><br>
<input type=checkbox class=check name="work[]" id="work1-abwassermikrofiltration"
	value="abwassermikrofiltration" checked><label for="work1-abwassermikrofiltration"></label>
	<label for="work1-abwassermikrofiltration"
	>Abwasserbehandlung: Mikro-/Ultrafiltration</label><br>
<input type=checkbox class=check name="work[]" id="work1-abwasserneutralis"
	value="abwasserneutralis"><label for="work1-abwasserneutralis"></label>
	<label for="work1-abwasserneutralis"
	>Abwasserbehandlung: Neutralis</label><br>
<input type=checkbox class=check name="work[]" id="work1-abwasserbiologie"
	value="abwasserbiologie"><label for="work1-abwasserbiologie"></label>
	<label for="work1-abwasserbiologie"
	>Abwasserbehandlung: Biologie</label><br>
<input type=checkbox class=check name="work[]" id="work1-dampfkessel"
	value="dampfkessel"><label for="work1-dampfkessel"></label>
	<label for="work1-dampfkessel"
	>Dampfkessel: Abluft-Wärmetausch (ECO)</label><br>
<input type=checkbox class=check name="work[]" id="work1-dampfsystem"
	value="dampfsystem"><label for="work1-dampfsystem"></label>
	<label for="work1-dampfsystem"
	>Dampf-System: Brüdendampf-Nutzung</label><br>
</div><br>
<label class=left>sonstige Abwasserbehandlung</label>
<input type=text class=text name=abwasserandere value=""><br>
</div>
</div>

<div id=for-type-2>
<div class=input>
<label class=left>&nbsp;</label>
<div class=opts>
<input type=checkbox class=check name="work[]" id="work2-kontakt"
	value="kontakt"><label for="work2-kontakt"></label>
	<label for="work2-kontakt"
	>Kontaktwasseraufbereitung</label><br>
<input type=checkbox class=check name="work[]" id="work2-wasserrueck"
	value="wasserrueck" checked><label for="work2-wasserrueck"></label>
	<label for="work2-wasserrueck"
	>Wasserrückgewinnung</label><br>
<input type=checkbox class=check name="work[]" id="work2-kuehl"
	value="kuehl"><label for="work2-kuehl"></label>
	<label for="work2-kuehl"
	>Kühlwasserrückgewinnung</label><br>
</div>
</div>
</div>

<div id=for-type-3>
<div class=input>
<label class=left>&nbsp;</label>
<div class=opts>
<input type=checkbox class=check name="work[]" id="work3-kontakt"
	value="kontakt"><label for="work3-kontakt"></label>
	<label for="work3-kontakt"
	>Kontaktwasseraufbereitung</label><br>
<input type=checkbox class=check name="work[]" id="work3-wtabwasserfrisch"
	value="wtabwasserfrisch" checked><label for="work3-wtabwasserfrisch"></label>
	<label for="work3-wtabwasserfrisch"
	>Wärmetauscher Abwasser zu Frischwasser</label><br>
<input type=checkbox class=check name="work[]" id="work3-wrabluftzufwasser"
	value="wrabluftzufwasser"><label for="work3-wrabluftzufwasser"></label>
	<label for="work3-wrabluftzufwasser"
	>Wärmerückgewinnung Abluft zu Frischwasser</label><br>
<input type=checkbox class=check name="work[]" id="work3-wrabluftzufluft"
	value="wrabluftzufluft"><label for="work3-wrabluftzufluft"></label>
	<label for="work3-wrabluftzufluft"
	>Wärmerückgewinnung Abluft zu Frischluft</label><br>
<input type=checkbox class=check name="work[]" id="work3-wasserrueck"
	value="wasserrueck" checked><label for="work3-wasserrueck"></label>
	<label for="work3-wasserrueck"
	>Wasserrückgewinnung</label><br>
<input type=checkbox class=check name="work[]" id="work3-kuehl"
	value="kuehl"><label for="work3-kuehl"></label>
	<label for="work3-kuehl"
	>Kühlwasserrückgewinnung</label><br>
</div>
</div>
</div>

<script>
(function(){
function upddisplay() {
	var found = false;
	for (var i = 1; i <= 3; i++) {
		var r = document.getElementById("type-" + i);
		var e = document.getElementById("for-type-" + i);
		if (!r || !e)
			continue;
		if (r.checked) {
			e.style.display = '';
			found = true;
		} else
			e.style.display = 'none';
	}
	e = document.getElementById("worklabel");
	if (e)
		e.style.display = found ? '' : 'none';
}

function setonchange(r) {
	var old = r.onchange;
	r.onchange = function() {
		if (old)
			old();
		upddisplay();
	};
}

for (var i = 1; i <= 3; i++) {
	var r = document.getElementById("type-" + i);
	if (!r)
		continue;
	setonchange(r);
}

upddisplay();
})();
</script>

</div>

<div class=clearer></div>
<p>&nbsp;</p>

<div class=buttons>
<div class=right>
<input type="submit" name="save" value="speichern">
<input type="submit" name="cont" value="weiter">
</div>
<div class=left>
<input type="submit" name="back" value="abbrechen">
</div>
<div class=clearer></div>
</div>
</form>
